package com.manishrawat.realestate.servlet;
import com.manishrawat.realestate.dao.*; import com.manishrawat.realestate.model.User; import com.manishrawat.realestate.service.PropertyService; import jakarta.servlet.*; import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import java.io.*;
@WebServlet("/admin") public class AdminServlet extends HttpServlet{
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{try{User u=(User)r.getSession(false).getAttribute("user");if(!"ADMIN".equals(u.getRole())){s.sendError(403);return;}UserDAO users=new UserDAO();PropertyDAO props=new PropertyDAO();r.setAttribute("users",users.findAll());r.setAttribute("properties",new PropertyService().all());r.setAttribute("logs",new ActivityDAO().recent());r.setAttribute("userCount",users.count());r.setAttribute("pendingCount",props.countByStatus("PENDING"));r.setAttribute("approvedCount",props.countByStatus("APPROVED"));r.setAttribute("settings",new SettingsDAO().all());r.getRequestDispatcher("/WEB-INF/views/admin/index.jsp").forward(r,s);}catch(Exception e){throw new ServletException("Unable to load admin panel.",e);}}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws IOException{try{User u=(User)r.getSession(false).getAttribute("user");if(!"ADMIN".equals(u.getRole())){s.sendError(403);return;}String action=r.getParameter("action");ActivityDAO logs=new ActivityDAO();switch(action==null?"":action){case "propertyStatus"->{String status=r.getParameter("status");if(!java.util.List.of("APPROVED","REJECTED","PENDING").contains(status))throw new IllegalArgumentException();new PropertyDAO().setStatus(Integer.parseInt(r.getParameter("id")),status);logs.log(u.getId(),"Property listing status set to "+status);}
 case "userRole"->{int id=Integer.parseInt(r.getParameter("id"));if(id==u.getId())throw new IllegalArgumentException("You cannot change your own role.");new UserDAO().setRole(id,r.getParameter("role"));logs.log(u.getId(),"Changed user #"+id+" role");}
 case "userDelete"->{int id=Integer.parseInt(r.getParameter("id"));if(id==u.getId())throw new IllegalArgumentException("You cannot disable your own account.");new UserDAO().delete(id);logs.log(u.getId(),"Disabled user #"+id);}
 case "userState"->{int id=Integer.parseInt(r.getParameter("id"));if(id==u.getId())throw new IllegalArgumentException("You cannot change your own account state.");boolean active=Boolean.parseBoolean(r.getParameter("active"));new UserDAO().setActive(id,active);logs.log(u.getId(),(active?"Re-enabled":"Disabled")+" user #"+id);}
 case "setting"->{new SettingsDAO().put(r.getParameter("key"),r.getParameter("value"));logs.log(u.getId(),"Updated system setting "+r.getParameter("key"));}
 default->throw new IllegalArgumentException("Unsupported action.");}s.sendRedirect(r.getContextPath()+"/admin?saved=1");}catch(IllegalArgumentException e){s.sendRedirect(r.getContextPath()+"/admin?error=Please+check+the+admin+change");}catch(Exception e){throw new IOException("Unable to save admin changes.",e);}}
}
