package com.manishrawat.realestate.servlet;
import com.manishrawat.realestate.model.*; import com.manishrawat.realestate.service.PropertyService;
import jakarta.servlet.annotation.WebServlet; import jakarta.servlet.http.*; import jakarta.servlet.*; import java.io.*; import java.math.BigDecimal;
@WebServlet("/property") public class PropertyServlet extends HttpServlet{
 private final PropertyService ps=new PropertyService();
 protected void doGet(HttpServletRequest r,HttpServletResponse s)throws ServletException,IOException{try{User u=(User)r.getSession(false).getAttribute("user");String city=r.getParameter("city")==null?"":r.getParameter("city").trim();String type=r.getParameter("type")==null?"":r.getParameter("type").trim();if(city.length()>80||!type.isEmpty()&&!java.util.List.of("Apartment","House","Villa").contains(type)){r.setAttribute("properties",java.util.List.of());r.setAttribute("searchError","Check the city and property type filters.");}else r.setAttribute("properties",ps.search(city,type));if("MANAGER".equals(u.getRole())){r.setAttribute("myProperties",ps.manager(u.getId()));if(r.getParameter("editId")!=null){try{Property p=new com.manishrawat.realestate.dao.PropertyDAO().findById(Integer.parseInt(r.getParameter("editId")));if(p!=null&&p.getManagerId()==u.getId())r.setAttribute("editProperty",p);}catch(NumberFormatException invalidId){r.setAttribute("searchError","That listing could not be opened for editing.");}}}r.getRequestDispatcher("/WEB-INF/views/properties.jsp").forward(r,s);}catch(Exception e){throw new ServletException("Unable to load properties.",e);}}
 protected void doPost(HttpServletRequest r,HttpServletResponse s)throws IOException{try{User u=(User)r.getSession(false).getAttribute("user");if(!"MANAGER".equals(u.getRole())){s.sendError(403,"Only Property Managers can manage listings.");return;}String action=r.getParameter("action");if(action==null||!java.util.List.of("create","update","delete").contains(action))throw new IllegalArgumentException();int id=r.getParameter("id")==null?0:Integer.parseInt(r.getParameter("id"));if("delete".equals(action)){ps.delete(id,u.getId());}else{Property p=new Property();p.setManagerId(u.getId());p.setTitle(clean(r.getParameter("title"),150));p.setAddress(clean(r.getParameter("address"),255));p.setCity(clean(r.getParameter("city"),80));String rent=r.getParameter("rent");if(rent==null)rent=r.getParameter("price");p.setRent(new BigDecimal(rent));p.setPropertyType(clean(r.getParameter("type"),50));p.setBedrooms(Integer.parseInt(r.getParameter("bedrooms")));String description=r.getParameter("description");p.setDescription(description==null?"":description.trim());if(p.getRent().signum()<=0||p.getRent().compareTo(new BigDecimal("9999999999.99"))>0||p.getRent().stripTrailingZeros().scale()>2||p.getBedrooms()<0||p.getBedrooms()>50||p.getDescription().length()>4000)throw new IllegalArgumentException();if("update".equals(action)){p.setId(id);ps.update(p,u.getId());}else ps.create(p);}s.sendRedirect(r.getContextPath()+"/property?saved=1");}catch(IllegalArgumentException e){s.sendRedirect(r.getContextPath()+"/property?error=Check+the+listing+details");}catch(Exception e){throw new IOException("Unable to save listing.",e);}}
 private String clean(String x,int max){if(x==null||x.isBlank()||x.length()>max)throw new IllegalArgumentException();return x.trim();}
}
