package com.manishrawat.realestate.dao;
import com.manishrawat.realestate.model.Property; import com.manishrawat.realestate.util.DBConnection; import java.sql.*; import java.util.*;
public class PropertyDAO implements GenericRepository<Property>{
 public int save(Property x)throws Exception{String q="INSERT INTO properties(manager_id,title,address,city,price,property_type,bedrooms,description,status) VALUES(?,?,?,?,?,?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q,Statement.RETURN_GENERATED_KEYS)){p.setInt(1,x.getManagerId());p.setString(2,x.getTitle());p.setString(3,x.getAddress());p.setString(4,x.getCity());p.setBigDecimal(5,x.getPrice());p.setString(6,x.getPropertyType());p.setInt(7,x.getBedrooms());p.setString(8,x.getDescription());p.setString(9,"PENDING");p.executeUpdate();ResultSet k=p.getGeneratedKeys();return k.next()?k.getInt(1):0;}}
 public void setStatus(int id,String s)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE properties SET status=? WHERE id=?")){p.setString(1,s);p.setInt(2,id);p.executeUpdate();}}
 public List<Property> findAll()throws Exception{return query("SELECT * FROM properties ORDER BY id DESC",-1);}
 public List<Property> approved(String city,String type)throws Exception{String q="SELECT * FROM properties WHERE status='APPROVED' AND (?='' OR city LIKE ?) AND (?='' OR property_type=?) ORDER BY id DESC";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,city);p.setString(2,"%"+city+"%");p.setString(3,type);p.setString(4,type);return mapList(p.executeQuery());}}
 public Property findById(int id)throws Exception{List<Property> l=query("SELECT * FROM properties WHERE id="+id,-1);return l.isEmpty()?null:l.get(0);}
 public List<Property> findByManager(int id)throws Exception{return query("SELECT * FROM properties WHERE manager_id="+id,id);}
 public int countByStatus(String s)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM properties WHERE status=?")){p.setString(1,s);ResultSet r=p.executeQuery();r.next();return r.getInt(1);}}
 private List<Property> query(String q,int ignored)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){return mapList(p.executeQuery());}}
 private List<Property> mapList(ResultSet r)throws Exception{List<Property> l=new ArrayList<>();while(r.next()){Property x=new Property();x.setId(r.getInt("id"));x.setManagerId(r.getInt("manager_id"));x.setTitle(r.getString("title"));x.setAddress(r.getString("address"));x.setCity(r.getString("city"));x.setPrice(r.getBigDecimal("price"));x.setPropertyType(r.getString("property_type"));x.setBedrooms(r.getInt("bedrooms"));x.setDescription(r.getString("description"));x.setStatus(r.getString("status"));l.add(x);}return l;}
}
