package com.manishrawat.realestate.dao;
import com.manishrawat.realestate.model.*; import com.manishrawat.realestate.util.DBConnection; import java.sql.*; import java.util.*;
public class UserDAO implements GenericRepository<User>{
 public User login(String email,String pass)throws Exception{String q="SELECT * FROM users WHERE email=? AND is_active=TRUE";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setString(1,email);try(ResultSet r=p.executeQuery()){if(!r.next())return null;String stored=r.getString("password");boolean valid=stored!=null&&(stored.startsWith("$2")?com.manishrawat.realestate.util.PasswordUtil.matches(pass,stored):java.security.MessageDigest.isEqual(stored.getBytes(java.nio.charset.StandardCharsets.UTF_8),pass.getBytes(java.nio.charset.StandardCharsets.UTF_8)));if(!valid)return null;if(!stored.startsWith("$2")){try(PreparedStatement upgrade=c.prepareStatement("UPDATE users SET password=? WHERE id=?")){upgrade.setString(1,com.manishrawat.realestate.util.PasswordUtil.hash(pass));upgrade.setInt(2,r.getInt("id"));upgrade.executeUpdate();}}return map(r);}}}
 public boolean register(String n,String e,String p,String phone)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement s=c.prepareStatement("INSERT INTO users(name,email,password,role,phone) VALUES(?,?,?,?,?)")){s.setString(1,n);s.setString(2,e);s.setString(3,com.manishrawat.realestate.util.PasswordUtil.hash(p));s.setString(4,"TENANT");s.setString(5,phone);return s.executeUpdate()>0;}}
 public List<User> findAll()throws Exception{List<User> l=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM users ORDER BY id DESC");ResultSet r=p.executeQuery()){while(r.next())l.add(map(r));}return l;}
 public User findById(int id)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM users WHERE id=?")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}}
 public int count()throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM users WHERE is_active=TRUE")){try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}}
 public void updateProfile(int id,String name,String phone)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET name=?,phone=? WHERE id=?")){p.setString(1,name);p.setString(2,phone);p.setInt(3,id);p.executeUpdate();}}
 public void setRole(int id,String role)throws Exception{if(!List.of("ADMIN","MANAGER","TENANT").contains(role))throw new IllegalArgumentException("Invalid user role.");try(Connection c=DBConnection.getConnection()){c.setAutoCommit(false);try{String current;try(PreparedStatement p=c.prepareStatement("SELECT role FROM users WHERE id=? FOR UPDATE")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("User not found.");current=r.getString(1);}}if("ADMIN".equals(current)&&!"ADMIN".equals(role)){int admins=0;try(PreparedStatement p=c.prepareStatement("SELECT id FROM users WHERE role='ADMIN' FOR UPDATE");ResultSet r=p.executeQuery()){while(r.next())admins++;}if(admins<=1)throw new IllegalArgumentException("At least one administrator must remain.");}try(PreparedStatement p=c.prepareStatement("UPDATE users SET role=? WHERE id=?")){p.setString(1,role);p.setInt(2,id);p.executeUpdate();}c.commit();}catch(Exception e){c.rollback();throw e;}}}
 public void delete(int id)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET is_active=FALSE WHERE id=? AND role<>'ADMIN' AND is_active=TRUE")){p.setInt(1,id);if(p.executeUpdate()==0)throw new IllegalArgumentException("User not found or administrator accounts cannot be removed.");}}
 public void setActive(int id,boolean active)throws Exception{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement("UPDATE users SET is_active=? WHERE id=? AND role<>'ADMIN'")){p.setBoolean(1,active);p.setInt(2,id);if(p.executeUpdate()==0)throw new IllegalArgumentException("User not found or administrator accounts cannot be changed here.");}}
 private User map(ResultSet r)throws Exception{int i=r.getInt("id");String n=r.getString("name"),e=r.getString("email"),role=r.getString("role"),ph=r.getString("phone");User u=switch(role){case "ADMIN"->new Admin(i,n,e,"",ph);case "MANAGER"->new Manager(i,n,e,"",ph);default->new Tenant(i,n,e,"",ph);};u.setActive(r.getBoolean("is_active"));return u;}
}
